Ecma exercise
wolox-training/jb-react pull request #12
Opened 2019-03-29 22:19 UTC by JoaquinBattilana

## Summary

- Fixed all the test problems

## Screenshots

## Trello Card

https://trello.com/c/CcO2Le1d/6-js-stack-ii-ecma-6-7

2019-04-05 02:25 UTC, erikankodelia requested changes

2019-04-05 02:25 UTC, erikankodelia commented on react/finger-exercises/ecmascript/01 - spread/index.js
> +}
You can return directly: return isArray(obj) ? [...obj] : { ...obj };

2019-04-05 02:25 UTC, erikankodelia commented on react/finger-exercises/ecmascript/02 - promises/index.js
> +  return Date.now() - startTime;
You can return directly delay(time).

2019-04-10 21:08 UTC, gon-escalante approved these changes

2019-04-11 16:30 UTC, erikankodelia approved these changes

2019-04-12 17:44 UTC, merged