Tic tac toe
wolox-training/jb-react pull request #14
Opened 2019-04-04 17:49 UTC by JoaquinBattilana

## Summary

Made tic tac toe react tutorial app

## Screenshots

![tic-tac-toe](https://user-images.githubusercontent.com/23125063/55576875-a9a3da80-56e8-11e9-9c50-de9a0708055e.gif)

## Trello Card

https://trello.com/c/fNc5Zjgs/42-react-app-tic-tac-toe

2019-04-05 02:40 UTC, erikankodelia requested changes

2019-04-05 02:40 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Game/components/Board/index.js
> +      <React.Fragment>
You can write:

 import React, { Component, Fragment } from 'react';

And then you don't need to write React.Fragment

2019-04-05 02:40 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Game/components/Square/index.js
> +import {PropTypes} from 'prop-types';
You can write import PropTypes from 'prop-types'  or import { func, string } from 'prop-types'

2019-04-05 02:40 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Game/components/Square/index.js
> +function Square(props){
You can write function Square({ value, onClick }) and use directly without write props

2019-04-05 02:40 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +  handleClick = (i) => {
The parenthesis are not necessary

2019-04-05 02:40 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +    if (this.calculateWinner(current.squares) || squares[i]) {
You can use squares instead of current.squares

2019-04-05 02:40 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +      history: history.concat([{squares: squares}]),
You can write history: history.concat([{ squares }])

2019-04-05 02:40 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +      xIsNext: !this.state.xIsNext
When you update the state with a value in the state, try to use this:

this.setState(prevState => ({ 
  history: history.concat([{squares: squares}]),
  stepNumber: history.length,
   xIsNext: !prevState.xIsNext
})

2019-04-05 02:40 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +    const lines = [
You can create a constant file and move this array there

2019-04-05 02:40 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +            onClick={(i) => this.handleClick(i)}
You can write directly this.handleClick

2019-04-05 02:40 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +        <div className={styles.gameBoard}>
You can move this div inside of Board component

2019-04-10 22:23 UTC, gon-escalante requested changes

2019-04-10 22:23 UTC, gon-escalante commented on react/tic-tac-toe/src/app/screens/Game/components/Board/index.js
> +  onClick: PropTypes.func
you are missing `squares` in propTypes

2019-04-10 22:23 UTC, gon-escalante commented on react/tic-tac-toe/src/app/screens/Game/components/Board/index.js
> +import PropTypes from 'prop-types';
destructure here as you did in `Square`, for consistency 😄

2019-04-10 22:23 UTC, gon-escalante commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +  jumpTo(step){
define this as arrow function as you did with calculateWinner

2019-04-15 16:32 UTC, erikankodelia requested changes

2019-04-15 16:32 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Game/components/Square/index.js
> +function Square({value, onClick}){
Add an empty space between ) and {

2019-04-15 16:32 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Game/components/Board/index.js
> +        onClick = {() => this.props.onClick(i)}
You can pass as a prop the onClick function and 'i' as another prop. Then in the component square, you can create a method class that calls the function with 'i' as a param

2019-04-15 16:32 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Game/constants/index.js
> +export const lines = [
Write all in upper case when declarate a constant in a constant file

2019-04-15 16:32 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +    const history = this.state.history.slice(0, this.state.stepNumber + 1);
Extract keys from state:

 const { history, stepNumber, xIsNext } = this.state;

2019-04-15 16:32 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +  jumpTo = step => {
The {} are not necessary

2019-04-15 16:32 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +  calculateWinner = (squares) => {
The () are not necessary

2019-04-15 16:32 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +      status = 'Winner: ' + winner;
It is great! but you can do it like this too:

`Winner: ${winner}`

2019-04-15 16:32 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Game/index.js
> +          <div>{status}</div>
This div doesn't have any className and it only has one child, so you can remove the div

2019-04-17 19:24 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Game/components/Board/index.js
> +        onClick={this.props.onClick}
For no repeate this.props you can extract the keys.

const { squares, onClick } = this.props;

2019-04-17 19:24 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Game/components/Square/index.js
> +  }
Add a space after this method

2019-04-17 19:36 UTC, erikankodelia approved these changes

2019-04-17 20:02 UTC, merged