Login layout
wolox-training/jb-react pull request #18
Opened 2019-04-25 18:51 UTC by JoaquinBattilana

## Summary

-Developed login view with react-form
-Front end validation of required field, minimum password length and valid email

## Screenshots

![login-layout](https://user-images.githubusercontent.com/23125063/56760607-f0c63e00-6771-11e9-9be9-6b90f6703d61.gif)

## Trello Card

https://trello.com/c/5UzSnwKm/52-routing-i-layout

2019-04-26 22:40 UTC, erikankodelia requested changes

2019-04-26 22:40 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Login/components/CustomInput/index.js
> +      <input {...input}
I think that this component has linter warnings

2019-04-26 22:40 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Login/components/LoginForm/layout.js
> +  const aux = false;
Remove this line

2019-04-26 22:40 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Login/components/LoginForm/layout.js
> +      <button type="submit" className={styles.submitButton} disabled={invalid} >{FORM_SUBMIT_BUTTON}</button>
Remove the extra space between invalid} and >

2019-04-30 15:26 UTC, gon-escalante requested changes
great work! 👏 , just some code style comments

2019-04-30 15:26 UTC, gon-escalante commented on react/tic-tac-toe/src/app/screens/Login/components/CustomInput/styles.module.scss
> +}
enter

2019-04-30 15:26 UTC, gon-escalante commented on react/tic-tac-toe/src/app/screens/Login/components/LoginForm/index.js
> +export default LoginFormContainer;
enter

2019-04-30 15:26 UTC, gon-escalante commented on react/tic-tac-toe/src/app/screens/Login/components/LoginForm/layout.js
> +export default LoginForm;
enter

2019-04-30 15:26 UTC, gon-escalante commented on react/tic-tac-toe/src/app/screens/Login/components/CustomInput/index.js
> +function CustomInput ( { label, input, type, meta } ) {
`({ stuff })`

2019-04-30 15:26 UTC, gon-escalante commented on react/tic-tac-toe/src/app/screens/Login/components/CustomInput/index.js
> +      { meta.error && meta.touched &&
`{meta...` also you seem to be indenting with 4 spaces in some cases

2019-04-30 15:26 UTC, gon-escalante commented on react/tic-tac-toe/src/app/screens/Login/components/LoginForm/index.js
> +    // here we handle de submit
`// TODO: add submit handling` or something like that 😛

2019-04-30 15:26 UTC, gon-escalante commented on react/tic-tac-toe/src/app/screens/Login/components/LoginForm/index.js
> +    return <LoginForm handleSubmit={this.handleSubmit} invalid={invalid}/>;
add space in `...invalid} />`

2019-04-30 15:26 UTC, gon-escalante commented on react/tic-tac-toe/src/app/screens/Login/components/LoginForm/styles.module.scss
> +}
enter

2019-04-30 15:26 UTC, gon-escalante commented on react/tic-tac-toe/src/app/screens/Login/styles.module.scss
> +}
enter

2019-04-30 15:26 UTC, gon-escalante commented on react/tic-tac-toe/src/constants/text.js
> +export const FORM_SUBMIT_BUTTON = "Sign in";
enter

2019-05-02 19:02 UTC, erikankodelia requested changes

2019-05-02 19:02 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Login/index.js
> +    return (
This component has linter warning because of there more spaces

2019-05-02 19:02 UTC, erikankodelia commented on react/tic-tac-toe/src/constants/index.js
> +export const EMAILRE = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
Add empty line before this line

2019-05-07 16:48 UTC, gon-escalante approved these changes

2019-05-07 16:49 UTC, erikankodelia requested changes

2019-05-07 16:49 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Login/components/CustomInput/styles.module.scss
> +  margin: 10px 0;
Change to margin-bottom: 10px and in the label class change to 20px

2019-05-07 16:49 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Login/components/LoginForm/styles.module.scss
> +  width: 500px;
Change to max-width: 500px and width: 100%

2019-05-07 16:49 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Login/components/LoginForm/styles.module.scss
> +    width: 100px;
Same here

2019-05-08 18:08 UTC, erikankodelia approved these changes

2019-05-09 15:59 UTC, merged