Login router + local storage
wolox-training/jb-react pull request #19
Opened 2019-05-03 21:03 UTC by JoaquinBattilana

## Summary

- Added redux thunk for async dispatches
-Used local storage for persisting the session
-Used react router for simple routing between login and game

## Screenshots

![login-router](https://user-images.githubusercontent.com/23125063/57165500-a70ed080-6dcd-11e9-934a-090f7ac7e999.gif)

## Trello Card

https://trello.com/c/tMgUbW8E/50-routing-i-router

2019-05-07 16:57 UTC, erikankodelia requested changes

2019-05-07 16:57 UTC, erikankodelia commented on react/tic-tac-toe/src/app/components/ConditionalRedirect/index.js
> +  return <Redirect to={condition() ? first : second} />;
Why do you pass the function and not the value that return de fuction directly?

2019-05-07 16:57 UTC, erikankodelia commented on react/tic-tac-toe/src/app/utils/validate.js
> +export const isNotLogged = () => !window.localStorage.getItem('token');
It is not necessary this function, you can use !isLogged

2019-05-07 16:57 UTC, erikankodelia commented on react/tic-tac-toe/src/config/api/index.js
> +const api = create({
Add an empty line before

2019-05-07 21:26 UTC, gon-escalante approved these changes

2019-05-14 01:01 UTC, erikankodelia commented on react/tic-tac-toe/src/app/screens/Login/components/LoginForm/layout.js
> +      {hasError ? <h3 className={styles.inputError}>{WRONG_INPUT_TEXT}</h3> : null}
It is not necessary the null, you can write hasError && <h3 ...

2019-05-16 21:37 UTC, erikankodelia approved these changes

2019-05-17 00:10 UTC, merged